
name: Test Docker Gradle
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: pangzineng/Github-Action-One-Click-Docker@master

