name: Test Docker Gradle
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Dump GitHub context
      run: echo "${{ toJson(github) }}"
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: docker build . -t ${{ secrets.DOCKER_OWNER }}/${{ github.ref }}:latest
    - name: Push Latest
      run: docker push ${{ secrets.DOCKER_OWNER }}/${{ github.ref }}:latest
